import {invoke} from './tauri.js';
import {pageRequest,previewFocusTarget} from './page-host.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function promptsListHtml(items){return items.length?items.map(p=>`<article class="connection-row"><div><strong>${esc(p.draft.name)}</strong><p>${new TextEncoder().encode(p.draft.body).length.toLocaleString()} 字节 · 本地提示词</p></div><div class="workspace-row-actions"><button type="button" class="mini-btn" data-prompt-preview="${esc(p.id)}">预览应用</button><button type="button" class="mini-btn" data-prompt-edit="${esc(p.id)}">编辑</button><button type="button" class="mini-btn" data-prompt-remove="${esc(p.id)}">移除</button></div></article>`).join(''):'<div class="sb-empty">还没有提示词。保存常用指令后，按需预览应用。</div>';}
export function pagePrompts(){return `<section class="prompts-space" data-prompts-root><div class="connections-toolbar"><p>共用提示词，按工具预览应用。</p><label class="sb-field"><span>应用到</span><select data-prompt-target aria-label="指令目标工具"><option value="codex">Codex</option><option value="claude">Claude Code · 默认目录</option></select></label><button type="button" class="mini-btn" data-prompts-refresh>刷新提示词</button></div><p role="status" aria-live="polite" data-prompts-status>打开后读取本地提示词。</p><div data-prompts-list></div><details data-prompt-editor><summary>添加提示词</summary><form class="sb-form" data-prompt-form><label class="sb-field"><span>名称</span><input name="name" required maxlength="160" autocomplete="off" aria-label="提示词名称"></label><label class="sb-field"><span>正文 · Markdown</span><textarea name="body" required maxlength="32768" rows="10" aria-label="提示词正文" spellcheck="false"></textarea></label><p class="model-scope">保存只更新提示词库，不改工具指令。正文最多 32 KiB，请使用凭据引用。</p><div class="actions"><button type="submit" class="mini-btn">保存提示词</button><button type="button" class="mini-btn" data-prompt-cancel>取消编辑</button></div></form></details><details data-prompt-backups><summary>指令备份与还原</summary><div data-prompt-backup-list></div></details><section data-prompt-confirm hidden class="mcp-confirm" role="dialog" aria-label="用户指令预览" aria-modal="true"><h2 data-prompt-plan-name></h2><p data-prompt-scope></p><div class="prompt-diff"><details><summary>当前指令</summary><pre data-prompt-before></pre></details><details open><summary>目标指令</summary><pre data-prompt-after></pre></details></div><p class="model-scope">将替换所选工具的完整用户指令，并先备份当前正文。其他规则保留；请开启新会话核对。</p><p role="alert" data-prompt-error></p><div class="actions"><button type="button" class="mini-btn" data-prompt-apply>确认写入</button><button type="button" class="mini-btn" data-prompt-dismiss>取消</button></div></section></section>`;}
export async function hydratePrompts(root){
 if(!root||root.promptsReady)return;root.promptsReady=true;
 const current=pageRequest(root),form=root.querySelector('form'),editor=root.querySelector('[data-prompt-editor]'),status=root.querySelector('[data-prompts-status]'),confirm=root.querySelector('[data-prompt-confirm]');let list=null,busy=false,editing=null,pending=null,caller=null,focusAfter=null;
 const targetSelect=root.querySelector('[data-prompt-target]');const target=()=>targetSelect.value;
 const dirty=()=>[...form.elements].filter(c=>['INPUT','TEXTAREA'].includes(c.tagName)).some(c=>c.value!==c.defaultValue);
 function fill(d=null){for(const name of ['name','body']){form.elements[name].value=d?.[name]??'';form.elements[name].defaultValue=form.elements[name].value;}form.reset();}
 function dismiss(){confirm.hidden=true;pending=null;confirm.querySelector('[data-prompt-before]').textContent='';confirm.querySelector('[data-prompt-after]').textContent='';for(const c of root.children)c.inert=false;const nav=root.closest('[data-model-workspace]')?.querySelector('.model-navigation');if(nav)nav.inert=false;focusAfter=caller;if(!busy&&focusAfter?.isConnected){focusAfter.focus({preventScroll:true});focusAfter=null;}}
 async function run(action){if(busy)return;busy=true;const controls=[...root.querySelectorAll('button,input,textarea,select')].map(c=>[c,c.disabled]);for(const[c]of controls)c.disabled=true;root.setAttribute('aria-busy','true');try{await action();}catch(e){if(current.ownsRequest())(pending?confirm.querySelector('[data-prompt-error]'):status).textContent=String(e?.message??e);}finally{busy=false;for(const[c,disabled]of controls)if(c.isConnected)c.disabled=disabled;root.removeAttribute('aria-busy');if(focusAfter?.isConnected){focusAfter.focus({preventScroll:true});focusAfter=null;}}}
 function rows(){root.querySelector('[data-prompts-list]').innerHTML=promptsListHtml(list.items);}
 async function read(){const next=await invoke('prompts_list');if(!current.ownsRequest())return;list=next;rows();root.dataset.pageReady='true';status.textContent='本地提示词 · 保存后可预览应用。';}
 async function readBackups(){const box=root.querySelector('[data-prompt-backup-list]');try{const next=await invoke('prompt_backups',{target:target()});if(!current.ownsRequest())return;box.innerHTML=next.length?next.map(b=>`<div class="prompt-backup"><span>${esc(b.name)}</span><button type="button" class="mini-btn" data-prompt-restore="${esc(b.name)}">预览还原</button></div>`).join(''):'<p class="model-scope">还没有指令备份。</p>';}catch{box.textContent='指令备份无法读取，请刷新重试。';}}
 async function preview(args,restore=false){args={...args,target:target()};const plan=await invoke(restore?'prompt_preview_restore':'prompt_preview',args);if(!current.ownsRequest())return;pending={plan,args,restore};confirm.hidden=false;confirm.querySelector('[data-prompt-plan-name]').textContent=restore?'还原用户指令':`应用 ${plan.name}`;confirm.querySelector('[data-prompt-scope]').textContent=plan.scope;confirm.querySelector('[data-prompt-before]').textContent=plan.before||'（空指令）';confirm.querySelector('[data-prompt-after]').textContent=plan.after||'（空指令）';confirm.querySelector('[data-prompt-error]').textContent='';for(const c of root.children)c.inert=c!==confirm;const nav=root.closest('[data-model-workspace]')?.querySelector('.model-navigation');if(nav)nav.inert=true;focusAfter=confirm.querySelector('[data-prompt-dismiss]');confirm.scrollIntoView({block:'nearest'});}
 targetSelect.onchange=()=>{if(busy||pending)return;root.querySelector('[data-prompt-backup-list]').textContent='';status.textContent=target()==='claude'?'Claude Code 默认用户目录 · 自定义目录不适用。':'Codex 用户指令';if(root.querySelector('[data-prompt-backups]').open)run(readBackups);};
 root.querySelector('[data-prompts-refresh]').onclick=()=>run(async()=>{await read();if(root.querySelector('[data-prompt-backups]').open)await readBackups();});
 root.querySelector('[data-prompt-cancel]').onclick=()=>{if(busy)return;editing=null;fill();editor.querySelector('summary').textContent='添加提示词';status.textContent='';};
 form.onsubmit=e=>{e.preventDefault();if(!list){status.textContent='先刷新读取提示词库；输入已保留。';return;}run(async()=>{const next=await invoke('prompt_save',{id:editing,draft:{name:form.elements.name.value,body:form.elements.body.value},expectedRevision:list.revision});if(!current.ownsRequest())return;list=next;editing=null;fill();rows();editor.querySelector('summary').textContent='添加提示词';status.textContent='已保存到本地，工具指令尚未改动。';});};
 root.querySelector('[data-prompts-list]').onclick=e=>{if(busy||!list)return;const button=e.target.closest('button');if(!button)return;if(dirty()){status.textContent='先保存或取消当前编辑。';return;}const id=button.dataset.promptEdit??button.dataset.promptPreview??button.dataset.promptRemove;const p=list.items.find(p=>p.id===id);if(!p)return;if(button.hasAttribute('data-prompt-edit')){editing=id;fill(p.draft);editor.open=true;editor.querySelector('summary').textContent='编辑提示词';form.elements.name.focus();}else if(button.hasAttribute('data-prompt-remove'))run(async()=>{const next=await invoke('prompt_remove',{id,expectedRevision:list.revision});if(!current.ownsRequest())return;list=next;if(editing===id){editing=null;fill();editor.querySelector('summary').textContent='添加提示词';}rows();status.textContent='已移除提示词，当前工具指令保留。';});else {caller=button;run(()=>preview({id,expectedRevision:list.revision}));}};
 root.querySelector('[data-prompt-backups]').ontoggle=()=>{if(root.querySelector('[data-prompt-backups]').open)run(readBackups);};
 root.querySelector('[data-prompt-backup-list]').onclick=e=>{const button=e.target.closest('[data-prompt-restore]');if(button&&!busy){if(dirty()){status.textContent='先保存或取消当前编辑。';return;}caller=button;run(()=>preview({name:button.dataset.promptRestore},true));}};
 root.querySelector('[data-prompt-dismiss]').onclick=dismiss;confirm.onkeydown=e=>{if(e.key==='Escape'&&!busy){e.preventDefault();e.stopPropagation();dismiss();}else if(e.key==='Tab'){e.preventDefault();const stops=[...confirm.querySelectorAll('summary,button:not(:disabled)')];previewFocusTarget(stops,document.activeElement,e.shiftKey)?.focus();}};
 root.querySelector('[data-prompt-apply]').onclick=()=>run(async()=>{if(!pending)return;const operation=pending;const result=await invoke(operation.restore?'prompt_restore':'prompt_apply',{...operation.args,planId:operation.plan.plan_id});if(!current.ownsRequest())return;dismiss();status.textContent=`${result.notice} 备份：${result.backup_name}${result.verified?'':' · 待核对'}`;if(root.querySelector('[data-prompt-backups]').open)await readBackups();});
 fill();await run(read);
}
