import { workspaceFlow, workspaceWritable, workspaceReceiptLabel } from './workspace-flow.js';
import {invoke} from './tauri.js';
import {pageRequest} from './page-host.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kinds={project:'项目任务',profile:'配置档位',layout:'窗口布局',tool:'智能体'};
export function workspaceStepsHtml(steps, receipts=new Map()) {
 return steps.map((s,i)=>{const r=receipts.get(s.kind), writable=workspaceWritable(s.kind);return `<li><div><small>${esc(kinds[s.kind]??'引用')}${writable?` · ${esc(workspaceReceiptLabel(r?.state))}`:''}</small><strong>${esc(s.name)}</strong>${s.reason?`<p>${esc(s.reason)}</p>`:''}${r?`<p>${esc(r.detail)}${r.backup?` 备份：${esc(r.backup)}`:''}</p>`:''}</div><div class="workspace-step-actions">${s.available?`<button type="button" class="mini-btn" data-workspace-step="${i}">${s.kind==='profile'?'预览档位':s.kind==='layout'?'预览布局':s.kind==='project'?'查看任务':'查看工具'}</button>`:'<span class="model-origin">不可用</span>'}${s.available&&r?.recoverable?`<button type="button" class="mini-btn" data-workspace-recover="${i}">${s.kind==='profile'?'查看恢复备份':r.historical?'查看恢复记录':'撤销入口'}</button>`:''}</div></li>`;}).join('');
}
export function workspaceHistoryHtml(records,windowRecords=[]){
 if(windowRecords.length){const merged=[...records.map(r=>({...r,kind:'profile'})),...windowRecords.map(r=>({...r,kind:'layout'}))].sort((a,b)=>b.created_ms-a.created_ms);const row=r=>`<li><span>${esc(new Date(r.created_ms).toLocaleString())} · ${r.kind==='layout'?'窗口':'配置'}</span><strong>${esc(r.kind==='layout'?{pending:'待核对',finished:'当时结果已记录',failed:'未执行'}[r.phase]??'待核对':{pending:'待核对',applied:'已写入',restored:'已还原',failed:'未完成'}[r.phase]??'待核对')}</strong>${r.kind==='layout'?`<small>${r.slots.length} 个窗口 · 历史位置需重新核对</small>`:r.backup_name?`<small>备份：${esc(r.backup_name)}</small>`:''}</li>`;return merged.slice(0,5).map(row).join('')+(merged.length>5?`<li><details><summary>更多记录 · ${merged.length-5} 条</summary><ul>${merged.slice(5).map(row).join('')}</ul></details></li>`:'');}
return records.length?records.map(r=>`<li><span>${esc(new Date(r.created_ms).toLocaleString())}</span><strong>${esc({pending:'待核对',applied:'已写入',restored:'已还原',failed:'未完成'}[r.phase]??'待核对')}</strong>${r.backup_name?`<small>备份：${esc(r.backup_name)}</small>`:''}</li>`).join(''):'<li>还没有配置操作记录。</li>';}
export function pageWorkspaces(){return `<section class="workspace-space" data-workspaces-root><div class="workspace-toolbar"><p>按项目保存常用组合，逐项预览和应用。</p><button type="button" class="mini-btn" data-workspace-refresh>刷新</button></div><p role="status" aria-live="polite" data-workspace-status>正在读取工作空间</p><div class="workspace-list" data-workspace-list></div><details class="workspace-editor" data-workspace-editor><summary>新建工作空间</summary><form data-workspace-form><label>名称<input name="name" required maxlength="80" autocomplete="off"></label><div class="workspace-fields"><label>项目<select name="project_id"><option value="">不指定</option></select></label><label>Codex 档位<select name="profile_id"><option value="">不指定</option></select></label><label>窗口布局<select name="layout_id"><option value="">不指定</option></select></label></div><details class="workspace-tool-picker"><summary>常用工具 · 可选</summary><fieldset><legend class="sr-only">选择工具</legend><div class="workspace-tools" data-workspace-tools></div></fieldset></details><div class="workspace-form-actions"><button type="submit" class="mini-btn">保存组合</button><button type="button" class="mini-btn" data-workspace-cancel>取消编辑</button></div></form></details><section data-workspace-preview hidden aria-label="工作空间核对"><div class="workspace-preview-head"><h2 data-workspace-title></h2><button type="button" class="mini-btn" data-workspace-close>关闭</button></div><p>逐项预览后应用，配置与窗口操作保留本地历史；项目与工具为查看入口。</p><ul data-workspace-steps></ul><details class="workspace-history"><summary>操作历史</summary><p class="model-scope" data-workspace-history-status></p><ul data-workspace-history></ul></details></section></section>`;}
export async function hydrateWorkspaces(navigate){
 const root=document.querySelector('[data-workspaces-root]');if(!root||root.workspaceReady)return;
 root.workspaceReady=true;const current=pageRequest(root),form=root.querySelector('form'),status=root.querySelector('[data-workspace-status]'),editor=root.querySelector('[data-workspace-editor]'),viewer=root.querySelector('[data-workspace-preview]');let list=null,catalog=null,busy=false,editing=null,preview=null,caller=null,focusAfter=null;
 const controls=()=>[...root.querySelectorAll('button,input,select')];
 const dirty=()=>[...form.querySelectorAll('input,select')].some(c=>(c.type==='checkbox'?String(c.checked):c.value)!==c.dataset.savedValue);
 function commit(){for(const c of form.querySelectorAll('input,select')){c.dataset.savedValue=c.type==='checkbox'?String(c.checked):c.value;if(c.type==='checkbox')c.defaultChecked=c.checked;else if(c.tagName==='SELECT'){for(const o of c.options)o.defaultSelected=o.selected;}else c.defaultValue=c.value;}form.reset();}
 function fill(d=null){form.elements.name.value=d?.name??'';for(const k of ['project_id','profile_id','layout_id'])form.elements[k].value=d?.[k]??'';for(const c of form.querySelectorAll('[data-workspace-tool]'))c.checked=d?.tools?.includes(c.value)??false;commit();}
 function options(select,rows){const value=select.value;select.innerHTML='<option value="">不指定</option>'+rows.map(c=>`<option value="${esc(c.id)}"${c.supported?'':' disabled'}>${esc(c.name)}${c.supported?'':' · 当前不支持'}</option>`).join('');if(value&&!rows.some(c=>c.id===value))select.insertAdjacentHTML('beforeend',`<option value="${esc(value)}">已失效的引用</option>`);select.value=value;}
 function renderCatalog(){for(const [field,key]of [['project_id','projects'],['profile_id','profiles'],['layout_id','layouts']])options(form.elements[field],catalog[key]);const selected=new Set([...form.querySelectorAll('[data-workspace-tool]:checked')].map(c=>c.value));if(!root.querySelector('[data-workspace-tools]').children.length)root.querySelector('[data-workspace-tools]').innerHTML=catalog.tools.map(c=>`<label><input type="checkbox" data-workspace-tool name="tools" value="${esc(c.id)}"${selected.has(c.id)?' checked':''}>${esc(c.name)}</label>`).join('');}
 function renderList(){root.querySelector('[data-workspace-list]').innerHTML=list.items.length?list.items.map(w=>`<article><div><strong>${esc(w.draft.name)}</strong><small>${[w.draft.project_id&&'项目',w.draft.profile_id&&'档位',w.draft.layout_id&&'布局',w.draft.tools.length&&`${w.draft.tools.length} 个工具`].filter(Boolean).join(' · ')}</small></div><div class="workspace-row-actions"><button type="button" class="mini-btn" data-workspace-open="${esc(w.id)}">打开组合</button><button type="button" class="mini-btn" data-workspace-edit="${esc(w.id)}">编辑</button><button type="button" class="mini-btn" data-workspace-remove="${esc(w.id)}">移除</button></div></article>`).join(''):'<div class="wb-empty">还没有工作空间。保存一个常用组合。</div>';
 root.querySelectorAll('[data-workspace-edit]').forEach(b=>b.onclick=()=>{if(busy)return;if(dirty()){status.textContent='先保存或取消当前编辑。';return;}editing=b.dataset.workspaceEdit;const w=list.items.find(w=>w.id===editing);fill(w.draft);editor.open=true;editor.querySelector('summary').textContent='编辑工作空间';form.elements.name.focus();});
 root.querySelectorAll('[data-workspace-open]').forEach(b=>b.onclick=()=>run(async(ownsFocus)=>{caller=b;const next=await invoke('workspace_preview',{id:b.dataset.workspaceOpen,expectedRevision:list.revision});if(!current())return;let records=[];let historyError='';try{records=await invoke('workspace_operations',{id:next.workspace.id});if(!Array.isArray(records))throw new Error();}catch{historyError='操作历史无法读取；当前页面记录保留，备份仍可在配置页查看。';}if(!current())return;let windowRecords=null;try{const history=await invoke('window_layout_history');if(!Array.isArray(history?.items))throw new Error();windowRecords=history.items.filter(r=>r.workspace?.id===next.workspace.id);}catch{historyError+=(historyError?' ':'')+'窗口历史读取失败；请在窗口页刷新核对。';}if(!current())return;workspaceFlow.open(next,records,windowRecords);root.querySelector('[data-workspace-history-status]').textContent=historyError;root.querySelector('[data-workspace-history]').innerHTML=workspaceHistoryHtml(records,windowRecords??[]);preview=next;viewer.hidden=false;root.querySelector('[data-workspace-title]').textContent=next.workspace.draft.name;renderProgress();focusAfter=viewer.querySelector('[data-workspace-close]');if(ownsFocus())viewer.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});status.textContent=next.steps.some(s=>!s.available)?'部分引用不可用，请逐项核对。':'组合已核对。';}));
 root.querySelectorAll('[data-workspace-remove]').forEach(b=>b.onclick=()=>run(async()=>{const next=await invoke('workspace_remove',{id:b.dataset.workspaceRemove,expectedRevision:list.revision});if(!current.ownsRequest())return;list=next;workspaceFlow.reconcile(next);preview=null;viewer.hidden=true;renderList();status.textContent='已移除组合；项目、档位和布局保留。';}));}
 function renderProgress(){
  if(!preview)return;
  const session=workspaceFlow.session;
  const same=session?.id===preview.workspace.id&&session.revision===preview.revision;
  if(same&&session.stale)status.textContent='组合需重新核对，请刷新后打开；已生成的备份仍在配置页。';
  root.querySelector('[data-workspace-steps]').innerHTML=workspaceStepsHtml(preview.steps,same?session.receipts:new Map());
  for(const button of viewer.querySelectorAll('[data-workspace-step],[data-workspace-recover]')){button.disabled=!!workspaceFlow.pending||!!session?.stale;button.onclick=()=>{
   try{const recovery=button.hasAttribute('data-workspace-recover'),step=preview.steps[Number(recovery?button.dataset.workspaceRecover:button.dataset.workspaceStep)];workspaceFlow.activate(step,recovery);navigate(step,recovery?workspaceFlow.receipt(step.kind):null);}
   catch(error){status.textContent=error.message;}
  };}
 }
 root.renderWorkspaceProgress=renderProgress;
 async function run(action){if(busy)return;const initiator=document.activeElement,ownsFocus=()=>document.activeElement===initiator||document.activeElement===document.body;busy=true;const before=controls().map(c=>[c,c.disabled]);for(const[c]of before)c.disabled=true;root.setAttribute('aria-busy','true');try{await action(ownsFocus);}catch(e){if(current.ownsRequest()){status.textContent=e?.message??String(e);preview=null;viewer.hidden=true;}}finally{busy=false;for(const[c,disabled]of before)if(c.isConnected)c.disabled=disabled;root.removeAttribute('aria-busy');if(current()&&ownsFocus()&&focusAfter?.isConnected&&!focusAfter.disabled){focusAfter.focus({preventScroll:true});}focusAfter=null;}}
 async function read(){await run(async()=>{const [next,choices]=await Promise.all([invoke('workspaces_list'),invoke('workspace_catalog')]);if(!current.ownsRequest())return;list=next;workspaceFlow.reconcile(next);catalog=choices;const wasDirty=dirty();renderCatalog();if(!wasDirty)commit();renderList();preview=null;viewer.hidden=true;status.textContent=choices.errors.join('；');root.dataset.pageReady='true';});}
 root.querySelector('[data-workspace-refresh]').onclick=read;
 form.onsubmit=e=>{e.preventDefault();if(!list||!catalog){status.textContent='请先刷新读取来源；输入已保留。';return;}const draft={name:form.elements.name.value,...Object.fromEntries(['project_id','profile_id','layout_id'].map(k=>[k,form.elements[k].value||null])),tools:[...form.querySelectorAll('[data-workspace-tool]:checked')].map(c=>c.value)};run(async()=>{const next=await invoke('workspace_save',{id:editing,draft,expectedRevision:list.revision});if(!current.ownsRequest())return;list=next;workspaceFlow.reconcile(next);editing=null;fill();editor.querySelector('summary').textContent='新建工作空间';renderList();preview=null;viewer.hidden=true;status.textContent='已保存到本机。';});};
 root.querySelector('[data-workspace-cancel]').onclick=()=>{if(busy)return;editing=null;fill();editor.querySelector('summary').textContent='新建工作空间';status.textContent='';};
 const close=()=>{
  const scroller=root.closest('.wb-content');
  scroller?.scrollTo({top:scroller.scrollTop,behavior:'instant'});
  viewer.hidden=true;preview=null;root.querySelector('[data-workspace-steps]').textContent='';
  if(caller?.isConnected){
   const target=caller;target.focus({preventScroll:true});
   // A queued smooth-scroll frame can land after close; return after that frame.
   requestAnimationFrame(()=>{if(current()&&viewer.hidden&&document.activeElement===target)target.scrollIntoView({block:'nearest',behavior:'instant'});});
  }
 };root.querySelector('[data-workspace-close]').onclick=close;viewer.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();}};
 fill();await read();
}
